version: 2
jobs:
  test:
    docker:
      - image: cimg/node:18.11.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn lint
      - run: yarn test
  release:
    docker:
      - image: cimg/node:18.11.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile
      - run: npx @continuous-auth/circleci-oidc-github-auth@1.0.4
      - run: npx semantic-release@17.4.5
workflows:
  version: 2
  test_and_release:
    # release when tests are successful
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - main
          context: cfa-release
